### ISSUE TITLE
主键冲突Bug 

### ISSUE THREAD

**Issue by sineava** [sineava/com.yuetu.io#5]
## serious
主键FVoucherID不是自增主键,金蝶K3新增有独立的主键数值,不是获取的表最后一条数据,导致金蝶插入会存在与凭证抽取冲突的冲突

**Comment by helloworld-liushijie** [comment]
## 不能从根本上解决问题
思路1: 让FVoucherID值大于一定数值(如1000000),避免冲突
思路2:让FVoucherID从0开始负数递减
## 表结构不能修改,否则会导致许多潜在问题
